.TH "savors-cloud" "7" "18 May 2021" "" ""
./"################################################################
.SH "NAME"
./"################################################################
\fBsavors-cloud\fP \(em plot text strings with font sized by frequency
or other count
./"################################################################
.SH "SYNOPSIS"
./"################################################################
.nf
env OPT=VAL... (ARGS... |...) |cloud --opt=val...
.fi
.PP
Display a word cloud view based on the given data pipeline.
./"################################################################
.SH "DESCRIPTION"
./"################################################################
The cloud view type plots strings (technically "n-grams") horizontally
and vertically to fill a rectangular region.  The font size used for
each string is scaled based on the relative frequency or other count of
the instances of the string in the data lines.  The size is only
relative and not directly proportional, so strings with bigger size have
a higher count than strings with smaller size, but the difference in
font size may not accurately reflect the scale of the difference in the
counts.  Fields that evaluate to traditional English "stop words" are
ignored.
./"################################################################
.SH "OPTIONS SUMMARY"
./"################################################################
The following options are specific to the cloud view.  See savors-view(7)
for additional options that are available to all views.  Defaults are
shown in brackets.  The \(cq\&=\(cq\& for options that take a parameter
is optional; whitespace may be used instead.  Detailed descriptions are
given in following sections.
.PP
.nf
\-\-count=EVAL  expression to increment by [1]
\-\-font=PATH   path to alternate font
\-\-ngram=INT   length of word sequences [1]
.fi
./"################################################################
.SH "OPTIONS"
./"################################################################
See savors-view(7) for detailed descriptions of the options that
are available to all views.
.IP "\fB\-\-count=EVAL\fP"
A Savors expression (see savors-expr(7)) that will be evaluated against
each data line to determine how much to add to the count of each n-gram.
The default is 1, which simply counts the frequency of each ngram.
.IP "\fB\-\-font=PATH\fP"
The path to an alternate font file.  By default, the open source
DejaVuSansCondensed font is used, which is included in the Savors
distribution.
.IP "\fB\-\-ngram=INT\fP"
Plot fields as n-grams of the given size.  For example, if field values
were ("one", "two", "three"), \fB\-\-ngram=2\fP would increase the
counts for both "one two" and "two three" and plot them separately while
\fB\-\-ngram=3\fP would increase the count and plot only "one two
three".  The default is 1, where each given field is counted and
plotted separately.
./"################################################################
.SH "EXAMPLES"
./"################################################################
Show a word cloud of the number of times each non-root user is running
a particular command on the system.  In this example, the top command is
invoked in batch mode to collect running processes with the time
extracted from the header emitted periodically.  The user and command
name are plotted as a 2-gram every 10 seconds using the default
frequency count.
.PP
.RS
.nf
env grep='^\s*\d' grep_v=' root ' time=f3 time_grep='^top' top -b -d 10 \\
	|cloud --color=f12 --fields=f2,f12 --period=10 --ngram=2
.fi
.RE
./"################################################################
.SH "FILES"
./"################################################################
/etc/savorsrc
.RS
This file specifies various global configuration items including
screen and geometry preferences, file paths, default options, and
preconfigured views.  See savorsrc(5).
.RE
.PP
$HOME/.savorsrc
.RS
This file specifies per user overrides of global configuration and
saved views.  See savorsrc(5).
.RE
./"################################################################
.SH "AUTHOR"
./"################################################################
Savors was written by Paul Kolano.
./"################################################################
.SH "SEE ALSO"
./"################################################################
savors(1), savors-axis(7), savors-chart(7), savors-data(7),
savors-expr(7), savors-graph(7), savors-grid(7), savors-map(7),
savors-rain(7), savors-tree(7), savors-view(7), savorsrc(5)
